name: bebek_takip
description: "Bebek takip uygulamasÄ±"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4





dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  intl: ^0.20.2
  google_fonts: ^6.3.3

  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  url_launcher: ^6.2.5
  package_info_plus: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/illustration/
    - assets/illustrations/tips/
    - assets/app_icon/
    - assets/onboarding/
